import { StyleSheet } from "react-native"
import { BGC, BGR, BGRDRK } from "../../Utils/Import";

const Style = StyleSheet.create({
   background:{
    backgroundColor:"#fff"
   },
   bgImage:{
    height:"100%",
    width:"100%",
    resizeMode:"cover"
   },
   contentView:{
    padding:20,
    height:"100%"
   },
   firstView:{
      padding:10,
      backgroundColor:BGR,
    //   paddingBottom:100,
      borderBottomRightRadius:30,
      borderBottomLeftRadius:30
   },
   searchMain:{
      flexDirection:"row",
      alignItems:"center"
   },
   searchBarStyle:{
      flexDirection:"row",
      alignItems:"center",
      backgroundColor:"#fff",
      paddingHorizontal:5,
      marginRight:5,
      borderRadius:10,
      width:"100%"
   },
   textInputStyle:{
      padding:5
   },
   UprIcon:{
      paddingHorizontal:5
   },
   addressStyle:{
      marginTop:10,
      flexDirection:"row",
      alignItems:"center",
      justifyContent:"space-between"
   },
   addressHeading:{
      flexDirection:"row",
      alignItems:"center",
   },
   nameView:{
      flexDirection:"row",
      alignItems:"center",
      marginTop:10
   },
   voucherView:{
      flexDirection:"row",
      alignItems:"center",
      marginTop:10
   },
   voucherInside:{
      flexDirection:"row",
      alignItems:"center",
      justifyContent:"space-between",
      backgroundColor:"#02424C",
      padding:10,
      borderRadius:10,
      marginHorizontal:2
   },
   secondView:{
      marginHorizontal:20,
      marginTop:10,
   },
   catgryView:{
      paddingHorizontal:15,
      backgroundColor:"#fff",
      elevation:5,
      paddingVertical:10,
      borderRadius:15
   },
   catFlatView:{
      marginHorizontal:5,
      paddingHorizontal:5
   },
   catFlatImage:{
      height:50,
      width:50,
      alignSelf:"center"
   },
   getOffView:{
      backgroundColor:BGR,
      marginTop:25,
      borderRadius:15,
      flexDirection:"row",
      justifyContent:"space-between",
      overflow:"hidden"
   },
   periodView:{
      backgroundColor: "#02424C",
      paddingVertical:5,
      borderRadius:10,
      paddingHorizontal:10,
      marginTop:5
   },
   offerInner:{
      padding:15
   },
   offerImageStyle:{
      height:120,
      width:120
   },
   iconBtnsView:{
      flexDirection:"row",
      alignItems:"center",
      justifyContent:"space-between"
   },
   seeMoreView:{
      marginTop:20,
      marginBottom:5,
   },
   textMoreInner:{
      flexDirection:"row",
      justifyContent:"space-between",
      alignItems:"center"
   },
   seeMoreStyle:{
      flexDirection:"row",
      justifyContent:"space-between",
      alignItems:"center"
   },
   itemsStyle:{
      borderTopLeftRadius:15,
      borderTopRightRadius:15,
      overflow:"hidden",
      marginHorizontal:6,
      marginTop:10,
      marginBottom:5,
      // elevation:3,
      backgroundColor:"#fff"
   },
   itemImage:{
      height:140,
      width:140,
   },
   addCartView:{
      borderWidth:1,
      borderColor:BGRDRK,
      paddingVertical:8,
      borderRadius:5,
      marginBottom:3
   },
   moreFlatStyle:{
   },
   itemFlatTextView:{
      paddingHorizontal:5
   }
})

export default Style;